### ISSUE TITLE
Add runtime configuration warning

### ISSUE THREAD

**Issue by OlivierBlanvillain** [OlivierBlanvillain/monadic-html#11]
Add an implicit parameter to the mount function with sensible default to configure what run time warning. Typical example we should be able so catch:

- `<input onClick={f}/>` instead of onclick
- `<input clazz="c"/>` instead of class
- `<inpu/>` instead of input
- `<div>foo</div>` instead of foo.toString

**Comment by olafurpg** [comment]
It would not have to be an implicit parameter, a regular parameter with default value is also fine.

**Comment by OlivierBlanvillain** [comment]
I've started working on this, should very straight forward to implement.

What do you think about exposing

```scala
trait Config {
  def transformElement(a: Any): String
  def transformAttributeKey(k: String): String
  def transformAttributeValue(a: Any): String
  ...
}
```

instead of

```scala
trait Config {
  def inspectElement(a: Any): Unit
  def inspectAttributeKey(k: String): Unit
  def inspectAttributeValue(a: Any): Unit
  ...
}
```

?

**Comment by olafurpg** [comment]
Are the `String` return values the warning messages that should go to the console? I would prefer to type parameterize the warning and output types and then have a method `emit` (or some other name) that ingests the warning type to an output

```scala
trait Config[A, B] {
  def emit(a: A): B
  def transformElement(a: Any): A
  def transformAttributeKey(k: String): A
  def transformAttributeValue(a: Any): A
```

The default implementation would then be `Config[String, Unit]` and print all warnings. The user could still in theory do anything they like such as build richer warning types, maybe redirect warnings to the sbt console, etc.

Over-engineering?

**Comment by OlivierBlanvillain** [comment]
I was thinking about these functions to "hot fix" stuff, like do the `onClick → onclick` transformation on the fly (in addition to side effectly printing warning to the console), but that's probably not such a good idea

**Comment by olafurpg** [comment]
Aah, I misunderstood the role of the config.

I'm not sure either whether "hot fixing" typos is a good idea. I can see it being occasionally convenient but it in the bigger picture it might allow you to be sloppy, which is bad IMO.

I guess it's best to leave this up to users. This design

```scala
trait Config {
  def transformElement(a: Any): String
  def transformAttributeKey(k: String): String
  def transformAttributeValue(a: Any): String
  ...
}
```

is incredibly flexible and it could be used in a ton of unexpected way to create developer/instrumentation tools. The power could be abused to hot fix typos, but I still think we should go with that.
