### ISSUE TITLE
Support first/per/post update foreach

### ISSUE THREAD

**Issue by OlivierBlanvillain** [OlivierBlanvillain/monadic-html#12]
Or something else equivalent to react component life-cycle.

**Comment by olafurpg** [comment]
For context: https://facebook.github.io/react/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class

Example use-case: I want to run highlightjs after some scala.xml.Xml has attached to the dom.

**Comment by OlivierBlanvillain** [comment]
Fixed in #38
