### ISSUE TITLE
Scala 2.12 version?

### ISSUE THREAD

**Issue by fsvehla** [OlivierBlanvillain/monadic-html#24]
Would be great to have

**Comment by OlivierBlanvillain** [comment]
I would like to wait and see what `scala-xml` does of the [Scala.js support pull request](https://github.com/scala/scala-xml/pull/109). If it's rejected (or takes much longer) I might cross publish another Scala.js build under my group id, but I would rather use the official one :)

**Comment by OlivierBlanvillain** [comment]
Fixed in latest release.
