### ISSUE TITLE
Allow Rx[Option[T]]

### ISSUE THREAD

**Issue by olafurpg** [OlivierBlanvillain/monadic-html#29]
Failing test

```scala
  test("Updating option attribute") {
    val id: Var[Option[String]] = Var(Option("oldId"))
    val hr: Elem = <hr id={id}/>
    val div = dom.document.createElement("div")
    mount(div, hr)
    assert(div.innerHTML == """<hr id="oldId">""")
    id := Option("newId")
    assert(div.innerHTML == """<hr id="newId">""")
    id := None
    assert(div.innerHTML == """<hr>""")
  }
// error

[info] - Updating option attribute *** FAILED *** (5 milliseconds)
[info]   "<hr id="[Some(oldId)]">" did not equal "<hr id="[oldId]">" (tests.scala:62)
```

**Comment by OlivierBlanvillain** [comment]
Don't you prefer being explicit here:?

```scala
val hr: Node = id.map(_.fold(<hr>)(i => <hr id={i}>))
```

This kind of custom magic can be achieved using the [transformAtom setting](https://github.com/OlivierBlanvillain/monadic-html/blob/e9ca96f7315e37ba3a06f0c1e9bec71d03251b67/monadic-html/src/main/scala/mhtml/settings.scala#L10-L11) for elements, and IIRC it was [not possible on attributes](https://github.com/OlivierBlanvillain/monadic-html/blob/e9ca96f7315e37ba3a06f0c1e9bec71d03251b67/monadic-html/src/main/scala/mhtml/mount.scala#L101)... But maybe it's doable now that we control the xml better?

**Comment by olafurpg** [comment]
The `<hr>` element could be a large form that I don't want to re-render on every update because I might loose focus on active `<input>` elements. I would prefer to pass in a `Rx[Option[T]]` to the attribute alone, leveraging precise binding.

**Comment by OlivierBlanvillain** [comment]
Do you have a use case where you actually want the attribute to be removed? Because `<hr id={id.getOrElse("")}>` should do the trick for `id`s...

**Comment by olafurpg** [comment]
Yes, for example `disabled` in `<form disabled>...</form>` should be removed if you want to activate that form. I could use null to remove the attribute, but I would prefer to use `Option[T]`.

**Comment by OlivierBlanvillain** [comment]
I see. It's weird with `disabled` because we can't even be express with `scala-xml`:

```scala
scala> <form disabled></form>
<console>:1: error: in XML literal: '=' expected instead of '>'
<form disabled></form>
              ^
<console>:1: error: in XML literal: ' or " delimited attribute value or '{' scala-expr '}' expected
<form disabled></form>
               ^
<console>:1: error: in XML literal: '>' expected instead of 'f'
<form disabled></form>
                 ^
```

**Comment by OlivierBlanvillain** [comment]
hmm

```scala
scala> <form disabled={Some(null)}></form>
res4: scala.xml.Elem = <form></form>

scala> <form disabled=""></form>
res5: scala.xml.Elem = <form disabled=""></form>
```

**Comment by olafurpg** [comment]
The semantics I want

```scala
scala> <form disabled={None}></form>
scala> <form disabled={false}></form>
res4: scala.xml.Elem = <form></form>

scala> <form disabled=""></form>
scala> <form disabled={Some("")}></form>
scala> <form disabled={true}></form>
res5: scala.xml.Elem = <form disabled=""></form>

scala> <form disabled={Some(null)}></form> // BOOM! runtime error. don't do that shit.
```
Binding.scala allows booleans as optional attributes and I think that's quite nice.

**Comment by OlivierBlanvillain** [comment]
Ok I'm sold for putting sementic into `Some`/`None`. These would be compile time errors otherwise, so we might as well do what the user most likely wants!

**Comment by olafurpg** [comment]
What about the booleans? It's really common in frameworks like bootstrap that you don't care about the value inside `Some(value)`, just if the attribute is active or not.

**Comment by OlivierBlanvillain** [comment]
I would personally be very surprised by 

```scala
scala> <form disabled={false}></form>
res4: scala.xml.Elem = <form></form>

scala> <form disabled={true}></form>
res5: scala.xml.Elem = <form disabled=""></form>
```

`None` / `Some("")` seams to make more sense for this output... but whatever

**Comment by olafurpg** [comment]
Cool. Boolean is a nice way to show that the value inside is irrelevant, this is the most common case in my experience.
