### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when assigning to Var

### ISSUE THREAD

**Issue by jrd-rocks** [OlivierBlanvillain/monadic-html#50]
The problem is found in `Var`'s `:=` method, copying subscribers at index -1 in the while loop. `i >=0` should be `i > 0` in https://github.com/OlivierBlanvillain/monadic-html/blob/master/monadic-rx/shared/src/main/scala/mhtml/rx.scala#L269

**Comment by OlivierBlanvillain** [comment]
Thanks for reporting! Somehow the rx tests were not run on the JVM :scream:...

**Comment by OlivierBlanvillain** [comment]
Fixed published as 0.3.1
